<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Flyaway Mortgage</name>
  <uuid>d5a787f2-c68b-42d1-87d6-c88ea745a526</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 
	Model is "Flyaway" then
set decision to the flyaway rule model computed from
      customer being customer ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
