<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Map output</name>
  <uuid>6f414ae3-7435-45d3-b35f-b51bbb7caad4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML Predictive Result where 
	the prediction is the prediction of 'ML model invocation' , 
	the probability is the maximum probability of 'ML model invocation' , 
    the product is "Cash";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
