<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Age 31 to 40</name>
  <uuid>4e267621-3072-4f36-b971-d8e4a166df12</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if  the age of customer is between 31 and 40 
then set the customer age range30 to40 of decision to 1; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
