<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Education - University</name>
  <uuid>ffcccaf6-c8c8-4872-8938-f9f5eadddb5a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the education level of customer is "University" 
then set the customer education level university of decision to 1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
