<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Employment - Unemployed</name>
  <uuid>0436d14f-9987-459b-85b4-655627d11c4a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the employment status of customer is "Unemployed" 
then set the customer employment status unemployed of decision to 1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
