<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Employment - Selfemployed</name>
  <uuid>0b243c71-1087-4925-b4eb-1ff31e4512fa</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the employment status of customer is "Self Employed" 
then set the customer employment status selfemployed of decision to 1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
