<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Employment - Employed</name>
  <uuid>62734305-705f-4fb6-9a83-3c86cd0ae519</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the employment status of customer is "Employed" 
then set the customer employment status employed of decision to 1 ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
