<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Employment - Homemaker</name>
  <uuid>85179064-29da-4d56-bbce-59e2eb7fdac4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the employment status of customer is "Homemaker" 
then set the customer employment status homemaker of decision to 1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
