<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Gender - Male</name>
  <uuid>ab35108b-976f-40fc-a474-3b1d191672ba</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the gender of customer is "Female"
then set the customer gender female of decision to 1 ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
