<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Internet Banking</name>
  <uuid>122855c1-d604-4bce-91a4-b29b0b4fe9bf</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if customer is internet banking flag 
then set the customer internet banking indicator of decision to 1 ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
