<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Marital Status - Married </name>
  <uuid>91ac1891-c332-4cfe-964e-9e17b9f571b8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the marital status of customer is "Married"
then set the customer marital status married of decision to 1; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
