<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Marital Status - Single</name>
  <uuid>5b875aef-f157-4440-96e3-5bd81ec9e406</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the marital status of customer is "Single"
then set the customer marital status single of decision to 1; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
