<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Marital Status - Divorced</name>
  <uuid>e46e5526-9783-4dd5-8939-19ec5e690dfd</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the marital status of customer is "Divorced"
then set the customer marital status divorced of decision to 1; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
