<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Urban Code - Rural</name>
  <uuid>6872afe3-10d5-4bb7-88bb-0d1b99272d2f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the uban code of customer is "Rural"
then set the customer urban code rural of decision to 1; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
