<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Urban Code - Urban</name>
  <uuid>63d05634-6bed-47bd-811b-060a6a633c22</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the uban code of customer is "Urban"
then set the customer urban code urban of decision to 1; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
