<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Urban Code - City</name>
  <uuid>2ed64fea-4ee6-499f-b4e3-dfde7aa6f976</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the uban code of customer is "City"
then set the customer urban code city of decision to 1; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
