<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Age 23 - 30</name>
  <uuid>54db32da-621d-4417-a1e3-50193cc731e3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if  the age of customer is between 23 and 30 
then set the customer age range23 to30 of decision to 1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
