<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Education - Uni</name>
  <uuid>2176c686-6761-49b9-a46f-85734a9faf30</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the education level of customer is "University" 
then set the customer education level university of decision to 1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
