<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Education - College</name>
  <uuid>ae50f552-a44f-42bc-ab8a-8032566d94a8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the education level of customer is "College" 
then set the customer education level college of decision to 1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
