<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Education - Phd</name>
  <uuid>66ddbb80-b225-4ae9-9585-e866b4d37fc0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the education level of customer is "Phd" 
then set the customer education level phd of decision to 1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
