<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Employment - Unemployed</name>
  <uuid>868aa6c6-9577-4497-adc4-cf94a553e571</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the employment status of customer is "Unemployed" 
then set the customer employment status unemployed of decision to 1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
