<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Internet Banking</name>
  <uuid>1230a5ff-ee69-4c23-acfd-0c7e182f39c3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if customer is internet banking flag 
then set the customer internet banking indicator of decision to 1 ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
