<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Marital Status - Single</name>
  <uuid>8472264e-cd52-4543-a814-91e30e50e858</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the marital status of customer is "Single"
then set the customer marital status single of decision to 1; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
