<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Marital Status - Divorced</name>
  <uuid>1ec84004-5360-45fe-b6be-5d9461742f4c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the marital status of customer is "Single"
then set the customer marital status single of decision to 1; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
