<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Market-Starting</name>
  <uuid>a9d775b6-cc8d-42de-abea-9a4a53b306ca</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the market group of customer is "Starting"
then set the customer market group starting of decision to 1; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
