<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Market - Spending</name>
  <uuid>00d53fe5-c40c-49d7-bd8d-af2eaca2ebda</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the market group of customer is "Spending"
then set the customer market group spending of decision to 1; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
