<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Cash</name>
  <uuid>ad4953d2-c75d-4942-be27-89c07ba3a5b9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 
	Model is "Cash" then
set decision to the cash model computed from
      customer being customer ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
