<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Map Output</name>
  <uuid>49c66b9c-24be-418b-9fc8-04314cc62f1c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML Predictive Result where 
	the prediction is the prediction of 'ML model invocation' , 
	the probability is the maximum probability of 'ML model invocation' , 
    the product is "Retirement";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
