<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Suggest Cash</name>
  <uuid>92ce6786-4277-4a87-9b03-89b8afcdfb08</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the probability of 'cash model prediction' is at least 0.6 
then
	add "Cash" to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
