<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Age Check</name>
  <uuid>2ea40918-2606-4561-b846-1d83145ade27</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the age of 'the customer' is at least 18 and less than 80
then
	set decision to "Good" ;
 
else set decision to "Bad"; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
