<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Defaults</name>
  <uuid>f7fe5406-9fea-423c-8f6b-08dd9f4dbc30</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML Predictive Result where
		the product is "Flyaway", 
		the prediction is 0, 
		the probability is 0.0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
