<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Probability</name>
  <uuid>83193444-54fb-4668-940f-37e89001428c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'overall score' to 80 + 30 ;
    set 'average score' to 'overall score' / 2; 

then set the probability of decision to 'average score' / 100 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
