<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>62a2302d-4c6a-45e3-8fae-08e33dd1ab19</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
