<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Consider Cash</name>
  <uuid>e9a3404c-a029-42c8-8c70-25d0e0cf8bb5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if all of the following conditions are true : 
	- the age of customer is between 19 and 75 
	- the employment status of customer is one of { "Employed", "Selfemployed", "Retired" } 
    - the income of customer is at least 55000 
then 
   add "Cash" to decision ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
