<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Default</name>
  <uuid>91a42c83-882f-4eeb-ae74-53fa15ea87f8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 100 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
