<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Copy Mediums - No Highs</name>
  <uuid>d6632bb2-667b-4d5d-b577-ee2ca5182b52</uuid>
  <documentation><![CDATA[Copy medium probability predictions in the absence of high priority predictions]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'a product recommendation' to a ML Predictive Result in 'Execute Models'; 
    
if the probability of 'a product recommendation' is between 0.65 and 0.8 
and there is no ML Predictive Result in 'Execute Models' 
	where the probability of this ML Predictive Result is more than 0.899, 
then 
	add 'a product recommendation' to decision ; 
    ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
