<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Copy Highs</name>
  <uuid>6e044c2b-90e0-4708-9168-f6b73f6c3459</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'a product recommendation' to a ML Predictive Result in 'Execute Models'; 
    
if the probability of 'a product recommendation' is more than 0.8 
then 
	add 'a product recommendation' to decision ; 
    print "Adding high probability offer : " + the product of 'a product recommendation' ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
