<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Create Empty List</name>
  <uuid>38a3190b-bad0-4e96-b187-27f4d5b7a249</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to an empty list of ML Predictive Results ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
