<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Retirement Model Criteria</name>
  <uuid>07782e16-061b-4d0f-b8d2-c1aec0d84020</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if all of the following conditions are true : 
	- the age of customer is between 25 and 50 
	- the employment status of customer is one of { "Employed", "Selfemployed"} 
    - the income of customer is at least 25000 
then 
   set decision to the retirement computed from
      customer being customer ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
